name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.17
        contrib_version:
          - "v0.45.1"
          - "v0.45.0"
          - "v0.44.0"
          - "v0.43.0"

    steps:
    - uses: actions/checkout@v2

    - name: Checkout Contrib ${{ matrix.contrib_version }}
      uses: actions/checkout@v2
      with:
        repository: open-telemetry/opentelemetry-collector-contrib
        path: opentelemetry-collector-contrib
        ref: ${{ matrix.contrib_version }}

    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}

    - name: Cache Go
      id: go-cache
      uses: actions/cache@v2
      env:
        cache-name: cache-go-modules
      with:
        path: |
          /home/runner/go/pkg/mod
          /home/runner/.cache/go-build
          /home/runner/go/bin
        key: v1-go-pkg-mod-${{ runner.os }}-${{ hashFiles('**/go.mod', '**/go.sum') }}

    - name: Go Mod Download
      run: go mod download
      working-directory: opentelemetry-collector-contrib

    - name: Build Collector
      run: make otelcontribcol
      working-directory: opentelemetry-collector-contrib

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Build Container Image
      #if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        #platforms: linux/amd64,linux/arm64
        platforms: linux/amd64
        #push: true
        push: false
        build-args:
        tags: 
          firefoxx04/otelcontrib:${{ matrix.contrib_version }}-go${{ matrix.go_version }}

      - name: Run Container with Test Config
        run: |
          docker run \
            -v ${PWD}/test/config.yaml:/config.yaml \
            firefoxx04/otelcontrib:${{ matrix.contrib_version }}-go${{ matrix.go_version }} --config /config.yaml

      - name: Install Cinc
        run: |
          curl -L https://omnitruck.cinc.sh/install.sh | \
          sudo bash -s -- -P cinc-auditor -v 4

      - name: Run Inspec Tests